// export const ActionTypes = {
//   SET_PRODUCTS: "SET_PRODUCTS",
//   SELECTED_PRODUCT: "SELECTED_PRODUCT",
//   REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
// };

export const ActionTypes = {
  ADD_IMAGES: "ADD_IMAGES",
  SET_LIKE: "SET_LIKE",
  UNSET_LIKE: "UNSET_LIKE",
};
